version: "0.0.1"
services:
  api:
    command: npm run start
    image: node:8
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3200:3200"
    working_dir: /usr/app
    environment:
       NODE_ENV: production
