version: "0.0.1"
services:
  web:
    build: .
    command: npm run start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3200:3200"

    environment:
       NODE_ENV: dev
