version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: svezday/machine-web-app:part-4-lite
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "8080:8080"
    networks:
      - webnet

networks:
  webnet:
